### ISSUE TITLE
invalid memory address or nil pointer dereference (in continuation of the issue #21)

### ISSUE THREAD

**Issue by biter777** [openconfig/grpctunnel#25]
In continuation of the [issue #21](https://github.com/openconfig/grpctunnel/issues/21)...

Thnx for your fix of #21.
The error has almost disappeared, but sometimes occurs.
As I noticed, the error occurs after closing the grpc server and starting agian...

Here is a brief explanation code and error text...

```
tunnelServer, err = tunnel.NewServer(cfg)
grpcServer = grpc.NewServer(opts...)
tpb.RegisterTunnelServer(grpcServer, tunnelServer)
l, err = net.Listen("tcp", ":7557")
go func{
  err := grpcServer.Serve(l)
  l.Close()
  donec <- err
}()
go func() {
  err := <-tunnelServer.ErrorChan()
  donec <- err
}()
[some code]
grpcServer.Stop()
l.Close()

// try to starting again and catch panic
tunnelServer, err = tunnel.NewServer(cfg)
grpcServer = grpc.NewServer(opts...)
tpb.RegisterTunnelServer(grpcServer, tunnelServer)
l, err = net.Listen("tcp", ":7557")
go func{
  err := grpcServer.Serve(l)
  l.Close()
  donec <- err
}()
go func() {
  err := <-tunnelServer.ErrorChan()
  donec <- err
}()
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xde1d12]

goroutine 21211595 [running]:
github.com/openconfig/grpctunnel/tunnel.(*Server).sendUpdate(0xc000618000, 0x11a9c80, 0xc007364030, 0xc0058fb4c0, 0x16, 0xc003788d00, 0x6, 0xc000618000, 0x0, 0x0)
	/home/biter/go/pkg/mod/github.com/openconfig/grpctunnel@v0.0.0-20210302145303-c8d84b22f3a1/tunnel/tunnel.go:642 +0x232
github.com/openconfig/grpctunnel/tunnel.(*Server).sendUpdates(0xc000618000, 0xc0058fb4c0, 0x16, 0xc003788d00, 0x6, 0x0, 0x0, 0x0)
	/home/biter/go/pkg/mod/github.com/openconfig/grpctunnel@v0.0.0-20210302145303-c8d84b22f3a1/tunnel/tunnel.go:662 +0x168
github.com/openconfig/grpctunnel/tunnel.(*Server).deleteTarget(0xc000618000, 0x11a9c80, 0xc00b9bb410, 0xc00273d310, 0x11a8500, 0x0, 0x0)
	/home/biter/go/pkg/mod/github.com/openconfig/grpctunnel@v0.0.0-20210302145303-c8d84b22f3a1/tunnel/tunnel.go:721 +0xd79
github.com/openconfig/grpctunnel/tunnel.(*Server).deleteTargets(0xc000618000, 0x11a9c80, 0xc00b9bb410, 0xc001fcb600, 0x0, 0x0)
	/home/biter/go/pkg/mod/github.com/openconfig/grpctunnel@v0.0.0-20210302145303-c8d84b22f3a1/tunnel/tunnel.go:749 +0x377
github.com/openconfig/grpctunnel/tunnel.(*Server).Register(0xc000618000, 0x11b7800, 0xc006b08a90, 0x11a2d20, 0xc000b00050)
	/home/biter/go/pkg/mod/github.com/openconfig/grpctunnel@v0.0.0-20210302145303-c8d84b22f3a1/tunnel/tunnel.go:793 +0x628
github.com/openconfig/grpctunnel/proto/tunnel._Tunnel_Register_Handler(0x10ec9a0, 0xc000618000, 0x11b5160, 0xc000656f00, 0x0, 0x0)
	/home/biter/go/pkg/mod/github.com/openconfig/grpctunnel@v0.0.0-20210302145303-c8d84b22f3a1/proto/tunnel/tunnel_grpc.pb.go:136 +0xdc
google.golang.org/grpc.(*Server).processStreamingRPC(0xc000b3e540, 0x11b7fe0, 0xc001001980, 0xc0030d3c00, 0xc0114e43f0, 0x16938a0, 0x0, 0x0, 0x0)
	/home/biter/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1457 +0x1592
google.golang.org/grpc.(*Server).handleStream(0xc000b3e540, 0x11b7fe0, 0xc001001980, 0xc0030d3c00, 0x0)
	/home/biter/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1537 +0xb09
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00107a380, 0xc000b3e540, 0x11b7fe0, 0xc001001980, 0xc0030d3c00)
	/home/biter/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871 +0xf4
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/biter/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:869 +0x2c5
```

**Comment by jxx-gg** [comment]
Can you please provide more details on how to reproduce it?  Is there some particular order of additions/deletions of targets that matters?

From the error log, seems it is trying to send subscription updates when deleting targets. I would not expect expect restarting the server to initiate any target deletion. I suspect it is from the `defer s.deleteClient(p.Addr)` in line 782,  which tries to clean things up.  Did you get the panic right after the closing the server? (you could let it sleep a while before starting a new server to check that).

**Comment by jxx-gg** [comment]
I suspect https://github.com/openconfig/grpctunnel/pull/26 could be a fix.

**Comment by biter777** [comment]
I will try to use the delay as you suggest. Let's see what happens.
But it seems to me, since the server has cleanup operations, there should be a Close() or Shutdown() method for that.

**Comment by gcsl** [comment]
Is this still an issue?
